### ISSUE TITLE
wt_download_report() is not working

### ISSUE THREAD

**Issue by LionelLeston** [ABbiodiversity/wildRtrax#14] opened 2023-09-18 19:28 UTC
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Brief description of the problem

The following code chunk is taking forever (2 hours 19 minutes so far) to download a single file from a folder that takes less time to download manually from the website. I have tried reinstalling the wildRtrax package.

```r
remotes::install_github("ABbiodiversity/wildRtrax")
#Attach package
library(wildRtrax)
Sys.setenv(WT_USERNAME = 'myUSERID', WT_PASSWORD = 'myPassword')#works
wt_auth()#works
my_projects <- wt_get_download_summary(sensor_id = 'ARU')
#Download the project report. Use ?wt_download_report to get options
my_report <- wt_download_report(project_id = 1321, sensor_id = 'ARU', reports="main", weather_cols = FALSE)#cols_def = F, 
#project 1321 is for Ruffed Grouse - BU Lab Project
#report options include "summary", "birdnet", "task", "tag", "definitions"
```

**Comment by agmacpha** [comment] 2023-09-18 19:42
@LionelLeston 

`system.time(result <- wt_download_report(project_id = 1321, sensor_id = 'ARU', reports = 'main', weather_cols = F))`

Downloading: 280 kB        

user  system elapsed 
  0.503   0.199  76.941 
  
  I get 76 seconds on a 134.13 / 10.07 MB Upload / Download speed test.
  
  Try `remotes::install_github("ABbiodiversity/wildRtrax", force = T)` and a speed test: https://www.speedtest.net/.

**Comment by LionelLeston** [comment] 2023-09-18 20:14
[image: image.png]
Still downloading and taking forever after forcing a new install.

Lionel

**Comment by LionelLeston** [comment] 2023-09-18 20:21
My laptop's hard drive is getting pretty full so maybe that's why it's
taking so long. Alternatively, maybe there's something about one of the
dependency packages that needs updating. But I've updated R and RStudio
(and possibly the packages) at least once since I started reporting this
problem. It may be a case of being able to show students how to use
wildRtrax to connect R and pull WildTrax data into R, without me being able
to do it myself and with me having to still manually download data.

Lionel

**Comment by dhope** [comment] 2024-02-16 20:26
I know you've closed this, but I have been experiencing the same issue as @LionelLeston and have been since at least when this issue was filed. Downloading data using the wildtrax API is super slow, to the point of being unusable. No way to do a `reprex` on this, but my suspicion is that it is the server side of Wildtrax or one of the dependencies like `curl::curl_download()` and not the R package that is causing the issue as I've tried downloading using `httr2` and have the same issues.


Also tried from different networks and different computers and still running into the same issue.

**Comment by agmacpha** [comment] 2024-02-27 21:01
@dhope @LionelLeston Could you provide a reprex for this Public project for these to see if you're getting similar download speeds?

`system.time(wt_download_report(887, 'PC', 'main', FALSE))`
  user  system elapsed                                                                                                                                                                                                     
  0.129   0.032   1.768

**Comment by dhope** [comment] 2024-02-28 16:06
``` r
library(wildRtrax)
library(dplyr)

Sys.setenv(WT_USERNAME = 'guest', WT_PASSWORD = 'Apple123')
wt_auth()
#> Authentication into WildTrax successful.


a <- wt_get_download_summary("PC")

x <- pull(a |> dplyr::filter(sensor=='PC'), project_id)

one_project_42kb <- bench::mark(wt_download_report(887, 'PC', 'main', FALSE))
#> Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB
one_project_512kb <- bench::mark(wt_download_report(889, 'PC', 'main', FALSE))
#> Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 49 kB     Downloading: 49 kB     Downloading: 49 kB     Downloading: 49 kB     Downloading: 57 kB     Downloading: 57 kB     Downloading: 74 kB     Downloading: 74 kB     Downloading: 74 kB     Downloading: 74 kB     Downloading: 90 kB     Downloading: 90 kB     Downloading: 110 kB     Downloading: 110 kB     Downloading: 120 kB     Downloading: 120 kB     Downloading: 120 kB     Downloading: 120 kB     Downloading: 130 kB     Downloading: 130 kB     Downloading: 130 kB     Downloading: 130 kB     Downloading: 140 kB     Downloading: 140 kB     Downloading: 160 kB     Downloading: 160 kB     Downloading: 160 kB     Downloading: 160 kB     Downloading: 160 kB     Downloading: 160 kB     Downloading: 160 kB     Downloading: 160 kB     Downloading: 180 kB     Downloading: 180 kB     Downloading: 190 kB     Downloading: 190 kB     Downloading: 200 kB     Downloading: 200 kB     Downloading: 210 kB     Downloading: 210 kB     Downloading: 220 kB     Downloading: 220 kB     Downloading: 240 kB     Downloading: 240 kB     Downloading: 240 kB     Downloading: 240 kB     Downloading: 250 kB     Downloading: 250 kB     Downloading: 260 kB     Downloading: 260 kB     Downloading: 270 kB     Downloading: 270 kB     Downloading: 280 kB     Downloading: 280 kB     Downloading: 280 kB     Downloading: 280 kB     Downloading: 290 kB     Downloading: 290 kB     Downloading: 290 kB     Downloading: 290 kB     Downloading: 300 kB     Downloading: 300 kB     Downloading: 320 kB     Downloading: 320 kB     Downloading: 320 kB     Downloading: 320 kB     Downloading: 330 kB     Downloading: 330 kB     Downloading: 330 kB     Downloading: 330 kB     Downloading: 340 kB     Downloading: 340 kB     Downloading: 350 kB     Downloading: 350 kB     Downloading: 350 kB     Downloading: 350 kB     Downloading: 360 kB     Downloading: 360 kB     Downloading: 380 kB     Downloading: 380 kB     Downloading: 380 kB     Downloading: 380 kB     Downloading: 380 kB     Downloading: 380 kB     Downloading: 390 kB     Downloading: 390 kB     Downloading: 390 kB     Downloading: 390 kB     Downloading: 410 kB     Downloading: 410 kB     Downloading: 410 kB     Downloading: 410 kB     Downloading: 410 kB     Downloading: 410 kB     Downloading: 440 kB     Downloading: 440 kB     Downloading: 460 kB     Downloading: 460 kB     Downloading: 470 kB     Downloading: 470 kB     Downloading: 470 kB     Downloading: 470 kB     Downloading: 470 kB     Downloading: 470 kB     Downloading: 500 kB     Downloading: 500 kB     Downloading: 500 kB     Downloading: 500 kB     Downloading: 510 kB     Downloading: 510 kB     Downloading: 510 kB     Downloading: 510 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 41 kB     Downloading: 41 kB     Downloading: 49 kB     Downloading: 49 kB     Downloading: 49 kB     Downloading: 49 kB     Downloading: 49 kB     Downloading: 49 kB     Downloading: 57 kB     Downloading: 57 kB     Downloading: 65 kB     Downloading: 65 kB     Downloading: 74 kB     Downloading: 74 kB     Downloading: 74 kB     Downloading: 74 kB     Downloading: 98 kB     Downloading: 98 kB     Downloading: 110 kB     Downloading: 110 kB     Downloading: 110 kB     Downloading: 110 kB     Downloading: 110 kB     Downloading: 110 kB     Downloading: 110 kB     Downloading: 110 kB     Downloading: 130 kB     Downloading: 130 kB     Downloading: 130 kB     Downloading: 130 kB     Downloading: 140 kB     Downloading: 140 kB     Downloading: 150 kB     Downloading: 150 kB     Downloading: 150 kB     Downloading: 150 kB     Downloading: 150 kB     Downloading: 150 kB     Downloading: 160 kB     Downloading: 160 kB     Downloading: 160 kB     Downloading: 160 kB     Downloading: 160 kB     Downloading: 160 kB     Downloading: 180 kB     Downloading: 180 kB     Downloading: 190 kB     Downloading: 190 kB     Downloading: 190 kB     Downloading: 190 kB     Downloading: 200 kB     Downloading: 200 kB     Downloading: 200 kB     Downloading: 200 kB     Downloading: 210 kB     Downloading: 210 kB     Downloading: 210 kB     Downloading: 210 kB     Downloading: 220 kB     Downloading: 220 kB     Downloading: 220 kB     Downloading: 220 kB     Downloading: 240 kB     Downloading: 240 kB     Downloading: 240 kB     Downloading: 240 kB     Downloading: 250 kB     Downloading: 250 kB     Downloading: 250 kB     Downloading: 250 kB     Downloading: 250 kB     Downloading: 250 kB     Downloading: 260 kB     Downloading: 260 kB     Downloading: 270 kB     Downloading: 270 kB     Downloading: 270 kB     Downloading: 270 kB     Downloading: 290 kB     Downloading: 290 kB     Downloading: 290 kB     Downloading: 290 kB     Downloading: 290 kB     Downloading: 290 kB     Downloading: 290 kB     Downloading: 290 kB     Downloading: 310 kB     Downloading: 310 kB     Downloading: 320 kB     Downloading: 320 kB     Downloading: 320 kB     Downloading: 320 kB     Downloading: 330 kB     Downloading: 330 kB     Downloading: 340 kB     Downloading: 340 kB     Downloading: 340 kB     Downloading: 340 kB     Downloading: 340 kB     Downloading: 340 kB     Downloading: 340 kB     Downloading: 340 kB     Downloading: 360 kB     Downloading: 360 kB     Downloading: 380 kB     Downloading: 380 kB     Downloading: 380 kB     Downloading: 380 kB     Downloading: 380 kB     Downloading: 380 kB     Downloading: 390 kB     Downloading: 390 kB     Downloading: 390 kB     Downloading: 390 kB     Downloading: 400 kB     Downloading: 400 kB     Downloading: 410 kB     Downloading: 410 kB     Downloading: 410 kB     Downloading: 410 kB     Downloading: 420 kB     Downloading: 420 kB     Downloading: 430 kB     Downloading: 430 kB     Downloading: 440 kB     Downloading: 440 kB     Downloading: 450 kB     Downloading: 450 kB     Downloading: 450 kB     Downloading: 450 kB     Downloading: 470 kB     Downloading: 470 kB     Downloading: 470 kB     Downloading: 470 kB     Downloading: 470 kB     Downloading: 470 kB     Downloading: 470 kB     Downloading: 470 kB     Downloading: 490 kB     Downloading: 490 kB     Downloading: 500 kB     Downloading: 500 kB     Downloading: 510 kB     Downloading: 510 kB     Downloading: 510 kB     Downloading: 510 kB
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.

ten_projects <- bench::mark(purrr::map(rep(887, 10), ~wt_download_report(.x, 'PC', 'main', FALSE)))
#> Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 41 kB     Downloading: 41 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 41 kB     Downloading: 41 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 8.2 kB     Downloading: 16 kB     Downloading: 16 kB     Downloading: 25 kB     Downloading: 25 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 33 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB     Downloading: 42 kB
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.

# Download a single small project
one_project_42kb$min
#> [1] 1.22s

# Download a single larger project
one_project_512kb$min
#> [1] 39.3s


# Download 10 projects
ten_projects$min
#> [1] 12.5s

glimpse(one_project_42kb)
#> Rows: 1
#> Columns: 13
#> $ expression <bch:expr> <wt_download_report(887, "PC", "main", FALSE)>
#> $ min        <bch:tm> 1.22s
#> $ median     <bch:tm> 1.22s
#> $ `itr/sec`  <dbl> 0.818181
#> $ mem_alloc  <bch:byt> 2.15MB
#> $ `gc/sec`   <dbl> 0
#> $ n_itr      <int> 1
#> $ n_gc       <dbl> 0
#> $ total_time <bch:tm> 1.22s
#> $ result     <list> [<data.frame[548 x 23]>]
#> $ memory     <list> [<Rprofmem[644 x 3]>]
#> $ time       <list> 1.22s
#> $ gc         <list> [<tbl_df[1 x 3]>]

glimpse(one_project_512kb)
#> Rows: 1
#> Columns: 13
#> $ expression <bch:expr> <wt_download_report(889, "PC", "main", FALSE)>
#> $ min        <bch:tm> 39.3s
#> $ median     <bch:tm> 39.3s
#> $ `itr/sec`  <dbl> 0.02542334
#> $ mem_alloc  <bch:byt> 43.8MB
#> $ `gc/sec`   <dbl> 0.07627003
#> $ n_itr      <int> 1
#> $ n_gc       <dbl> 3
#> $ total_time <bch:tm> 39.3s
#> $ result     <list> [<data.frame[29928 x 23]>]
#> $ memory     <list> [<Rprofmem[811 x 3]>]
#> $ time       <list> 39.3s
#> $ gc         <list> [<tbl_df[1 x 3]>]

glimpse(ten_projects)
#> Rows: 1
#> Columns: 13
#> $ expression <bch:expr> <purrr::map(rep(887, 10), ~wt_download_report(.x, "PC"…
#> $ min        <bch:tm> 12.5s
#> $ median     <bch:tm> 12.5s
#> $ `itr/sec`  <dbl> 0.07988607
#> $ mem_alloc  <bch:byt> 16MB
#> $ `gc/sec`   <dbl> 0.07988607
#> $ n_itr      <int> 1
#> $ n_gc       <dbl> 1
#> $ total_time <bch:tm> 12.5s
#> $ result     <list> [[<data.frame[548 x 23]>], [<data.frame[548 x 23]>], [<d…
#> $ memory     <list> [<Rprofmem[4620 x 3]>]
#> $ time       <list> 12.5s
#> $ gc         <list> [<tbl_df[1 x 3]>]
```

<sup>Created on 2024-02-28 with [reprex v2.1.0.9000](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.2 (2023-10-31 ucrt)
#>  os       Windows 11 x64 (build 22631)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  English_United States.utf8
#>  ctype    English_United States.utf8
#>  tz       America/New_York
#>  date     2024-02-28
#>  pandoc   3.1.1 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date (UTC) lib source
#>  bench         1.1.3      2023-05-04 [1] CRAN (R 4.3.2)
#>  class         7.3-22     2023-05-03 [2] CRAN (R 4.3.2)
#>  classInt      0.4-10     2023-09-05 [1] CRAN (R 4.3.2)
#>  cli           3.6.2      2023-12-11 [1] CRAN (R 4.3.2)
#>  codetools     0.2-19     2023-02-01 [2] CRAN (R 4.3.2)
#>  curl          5.2.0      2023-12-08 [1] CRAN (R 4.3.2)
#>  DBI           1.2.2      2024-02-16 [1] CRAN (R 4.3.2)
#>  digest        0.6.34     2024-01-11 [1] CRAN (R 4.3.2)
#>  dplyr       * 1.1.4      2023-11-17 [1] CRAN (R 4.3.2)
#>  e1071         1.7-14     2023-12-06 [1] CRAN (R 4.3.2)
#>  evaluate      0.23       2023-11-01 [1] CRAN (R 4.3.2)
#>  fansi         1.0.6      2023-12-08 [1] CRAN (R 4.3.2)
#>  fastmap       1.1.1      2023-02-24 [1] CRAN (R 4.3.2)
#>  fs            1.6.3      2023-07-20 [1] CRAN (R 4.3.2)
#>  furrr         0.3.1      2022-08-15 [1] CRAN (R 4.3.2)
#>  future        1.33.1     2023-12-22 [1] CRAN (R 4.3.2)
#>  generics      0.1.3      2022-07-05 [1] CRAN (R 4.3.2)
#>  globals       0.16.2     2022-11-21 [1] CRAN (R 4.3.1)
#>  glue          1.7.0      2024-01-09 [1] CRAN (R 4.3.2)
#>  hms           1.1.3      2023-03-21 [1] CRAN (R 4.3.2)
#>  htmltools     0.5.7      2023-11-03 [1] CRAN (R 4.3.2)
#>  httr          1.4.7      2023-08-15 [1] CRAN (R 4.3.2)
#>  intrval       0.1-2      2020-08-12 [1] CRAN (R 4.3.1)
#>  jsonlite      1.8.8      2023-12-04 [1] CRAN (R 4.3.2)
#>  KernSmooth    2.23-22    2023-07-10 [2] CRAN (R 4.3.2)
#>  knitr         1.45       2023-10-30 [1] CRAN (R 4.3.2)
#>  lattice       0.21-9     2023-10-01 [2] CRAN (R 4.3.2)
#>  lifecycle     1.0.4      2023-11-07 [1] CRAN (R 4.3.2)
#>  listenv       0.9.1      2024-01-29 [1] CRAN (R 4.3.2)
#>  lubridate     1.9.3.9000 2024-01-29 [1] https://ropensci.r-universe.dev (R 4.3.2)
#>  magick        2.8.3      2024-02-21 [1] https://r~
#>  magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.3.2)
#>  markdown      1.12       2023-12-06 [1] CRAN (R 4.3.2)
#>  MASS          7.3-60     2023-05-04 [2] CRAN (R 4.3.2)
#>  parallelly    1.37.0     2024-02-14 [1] CRAN (R 4.3.2)
#>  pillar        1.9.0      2023-03-22 [1] CRAN (R 4.3.2)
#>  pipeR         0.6.1.3    2016-04-04 [1] CRAN (R 4.3.2)
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.3.2)
#>  profmem       0.6.0      2020-12-13 [1] CRAN (R 4.3.2)
#>  progressr     0.14.0     2023-08-10 [1] CRAN (R 4.3.2)
#>  proxy         0.4-27     2022-06-09 [1] CRAN (R 4.3.2)
#>  purrr         1.0.2      2023-08-10 [1] CRAN (R 4.3.2)
#>  QPAD          0.0-3      2024-02-27 [1] Github (psolymos/QPAD@f103650)
#>  R.cache       0.16.0     2022-07-21 [1] CRAN (R 4.3.2)
#>  R.methodsS3   1.8.2      2022-06-13 [1] CRAN (R 4.3.1)
#>  R.oo          1.26.0     2024-01-24 [1] CRAN (R 4.3.2)
#>  R.utils       2.12.3     2023-11-18 [1] CRAN (R 4.3.2)
#>  R6            2.5.1      2021-08-19 [1] CRAN (R 4.3.2)
#>  Rcpp          1.0.12     2024-01-09 [1] CRAN (R 4.3.2)
#>  readr         2.1.5      2024-01-10 [1] CRAN (R 4.3.2)
#>  reprex        2.1.0.9000 2024-02-28 [1] Github (tidyverse/reprex@e1f65e9)
#>  rlang         1.1.3      2024-01-10 [1] CRAN (R 4.3.2)
#>  rmarkdown     2.25       2023-09-18 [1] CRAN (R 4.3.2)
#>  rstudioapi    0.15.0     2023-07-07 [1] CRAN (R 4.3.2)
#>  seewave       2.2.3      2023-10-19 [1] CRAN (R 4.3.2)
#>  sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.3.2)
#>  sf            1.0-15     2023-12-18 [1] CRAN (R 4.3.2)
#>  signal        1.8-0      2023-11-27 [1] CRAN (R 4.3.2)
#>  stringi       1.8.3      2023-12-11 [1] CRAN (R 4.3.2)
#>  stringr       1.5.1      2023-11-14 [1] CRAN (R 4.3.2)
#>  styler        1.10.2     2023-08-29 [1] CRAN (R 4.3.2)
#>  suntools      1.0.0      2023-07-06 [1] CRAN (R 4.3.2)
#>  terra         1.7-71     2024-01-31 [1] CRAN (R 4.3.2)
#>  tibble        3.2.1      2023-03-20 [1] CRAN (R 4.3.2)
#>  tidyr         1.3.1      2024-01-24 [1] CRAN (R 4.3.2)
#>  tidyselect    1.2.0      2022-10-10 [1] CRAN (R 4.3.2)
#>  tidyverse     2.0.0      2023-02-22 [1] CRAN (R 4.3.2)
#>  timechange    0.3.0      2024-01-18 [1] CRAN (R 4.3.2)
#>  tuneR         1.4.6      2023-11-27 [1] CRAN (R 4.3.2)
#>  tzdb          0.4.0      2023-05-12 [1] CRAN (R 4.3.2)
#>  units         0.8-5      2023-11-28 [1] CRAN (R 4.3.2)
#>  unmarked      1.4.1      2024-01-09 [1] CRAN (R 4.3.2)
#>  utf8          1.2.4      2023-10-22 [1] CRAN (R 4.3.2)
#>  vctrs         0.6.5      2023-12-01 [1] CRAN (R 4.3.2)
#>  wildRtrax   * 1.1.0      2024-02-27 [1] Github (ABbiodiversity/wildRtrax@056540e)
#>  withr         3.0.0      2024-01-16 [1] CRAN (R 4.3.2)
#>  xfun          0.42       2024-02-08 [1] CRAN (R 4.3.2)
#>  yaml          2.3.8      2023-12-11 [1] CRAN (R 4.3.2)
#> 
#>  [1] F:/R_LIB
#>  [2] C:/Users/hoped/AppData/Local/Programs/R/R-4.3.2/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by agmacpha** [comment] 2024-02-29 18:20
Thank you @dhope. Given this sits on the WildTrax side, we will work on improvements there to allow for a better experience in wildRtrax. I'll be closing this issue for now as the function is working as intended.

**Closed by agmacpha** 2024-02-29 18:20 UTC

**Comment by LionelLeston** [comment] 2024-02-29 18:22
Hi Alex, sorry I haven’t had time to do a reprex but it sounds like you’re
making headway all the same.
Lionel
