### ISSUE TITLE
authorization with a google account

### ISSUE THREAD

**Issue by kevinhawkshaw** [ABbiodiversity/wildRtrax#66] opened 2024-09-17 21:33 UTC
Hi there, when I log in to wildtrax, I use my google account, and I think this may be causing issues in authorization using the package. I'm definitely entering the correct username, because after several attempts I get blocked and get the notification on my google account, but my google password does not work with wt_auth(). Just wondering if there's a solution to be had, or if the package maybe doesn't function with google accounts yet.

Thanks,
Kevin

**Comment by agmacpha** [comment] 2024-09-18 16:34
Hi @kevinhawkshaw We're currently working on Google OAuth and public user authorization enhancements (see #48, #65 for current progress). I'll close this issue due to reproduction. 

In the meantime, you can create an OAuth user and password in the WildTrax login screen which will allow you to create credentials to use via `wt_auth()`

**Closed** 2024-09-18 16:34 UTC
